version: "3"

networks:
  indolent-retail-network:
    driver: "bridge"
    ipam:
      config:
        - gateway: "172.30.10.1"
          subnet: "172.30.10.0/24"

volumes: 
  postgres_db:

services:
  postgres:
    image: "postgres:16"
    restart: "unless-stopped"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      indolent-retail-network:
        ipv4_address: 172.30.10.100
    volumes:
      - "postgres_db:/var/lib/postgresql/data"